steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - asia-southeast1-docker.pkg.dev/ai-lab-16-gcp-505508/label-guardian/app:latest
      - .

images:
  - asia-southeast1-docker.pkg.dev/ai-lab-16-gcp-505508/label-guardian/app:latest

options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: "100"